### ISSUE TITLE
suggestion - more generic, for easier interfacing

### ISSUE THREAD

**Issue by dobkeratops** [tynril/rtriangulate#2]
how about 
(i) parameterising the float type so you can use f32 or f64 ... f32 is very common in graphics applications,

(iia) parameterising the *point* type, such that you can apply this algorithm to any existing data structure with vertex arrays, so long as it can supply .x() .y() (i.e. use a 2d point trait instead of a specific point type which users can impl on their data)

(iib) alternatively make it take [T;2] as the point type, as this is a 'dependancy-free' way of passing coordinate data between libraries

(iii) avoid impl'ing 'partialord' for the point type, instead using a 'sort_by' or whatever to get the ordering - to keep the specific (ambiguous) meaning of point ordering open for applications to do with as they please

**Comment by tynril** [comment]
Hey @dobkeratops,

This is a great idea. I've published version 0.3 of the crate, which introduces a generic `Point<T>` type, which allows you to use your own point type with the `triangulate` function, including with different float types. I've also removed the `PartialOrd` implementation, and instead, provided a utility `sort_points` function, which can be used with `sort_by` or `sort_unstable_by`. The new version is also about ~10% faster on my machine.

Sorry that it took so long, I hadn't seen the issue here. I must've missed the notification.
